### ISSUE TITLE
Yolomy website tasks view

### ISSUE THREAD

**Issue by Mwangik** [Mwangik/Yolomy#2]
## TODO

*Tasks to complete*
 * [x] header section -hero image and navigation bar
 * [x] filter checkboxes section with see all products link
 * [x] clothes,apparel and attires display section(2 rows 3 columns each)
 * [x] an about us section
 * [x] promo code section
 * [x] footer section
 * [x] making sure the website is mobile responsive

:point_up: :eyes: :ok_hand:
